routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);


Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', function () {
        return view('welcome');
    });
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('user', 'Admin\UserController');
    Route::resource('movie', 'Admin\MovieController');
});

app/Http/Controllers/Admin/MovieController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MovieRequest;
use App\Model\v1\Movie;
use Illuminate\Http\Request;

class MovieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $movies = Movie::paginate(10);
        return view('movie.index',compact('movies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('movie.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(MovieRequest $request)
    {
        $input = $request->all();
        $movie = Movie::create($input);
        return redirect(route('movie.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Movie::findOrFail($id)->delete();
        return back();
    }
}

app/Http/Controllers/v1/MovieController.php
<?php

namespace App\Http\Controllers\v1;

use App\Http\Controllers\Controller;
use App\Model\v1\Movie;
use Illuminate\Http\Request;

class MovieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $movies = Movie::paginate(10);
        return response()->json($movies, 200);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $movie = Movie::findOrFail($id);
        return response()->json($movie, 200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/movie/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('New Movie') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('movie.store') }}">
                        @csrf
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" name="name">
                        </div>
                        <div class="form-group">
                            <label for="email">Url</label>
                            <input type="text" class="form-control" id="email" name="url">
                        </div>
                        <div class="form-group col-md-4 text-center">
                            <label for="profile_image d-block">Image</label>
                            <div class="custom-file mt-3 d-block m-auto" style="width: 150px;height:150px;">
                                <div class="mb-4" style="width: 100%;height:100%;" class="position-relative">
                                    <img src="{{ $product->image ?? 'https://icons-for-free.com/iconfiles/png/512/add+photo+instagram+upload+icon-1320184027593509107.png' }}"
                                        id="thumbnail"
                                        class="img-responsive  img-thumbnail rounded-circle position-absolute" alt="image"
                                        style="width:150px;height:150px;">
                                    <input type="file" style="width: 100%;height:100%;top:0;left:0;"
                                        class=" custom-file-input" name="image"
                                        onchange="console.log(this.value);document.getElementById('thumbnail').src=window.URL.createObjectURL(this.files[0]);">
                                    <div class=" position-absolute img-thumbnail " style="bottom:0;right:0;">
                                        <i class="fa fa-image"></i> Upload
                                    </div>
                                </div>
                            </div>
                            <label for="profile_image d-block">Or using CDN :</label>


                            <input type="text" class="form-control" id="thumbnail_cdn" placeholder="https://example.com/..."
                                value="{{ $product->image ?? '' }}" name="image" aria-describedby="basic-addon3">
                            <button class="btn btn-outline-secondary btn-sm mt-3 text-center" type="button"
                                onclick="document.getElementById('thumbnail').src=document.getElementById('thumbnail_cdn').value;">Check</button>

                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <div class="card-footer">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/movie/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col">
            <div class="card">
                <!-- Card header -->
                <div class="card-header border-0">
                    <h3 class="mb-0">Movies <a href="{{ route('movie.create') }}" class="btn btn-sm btn-default ml-3">Add
                            New</a></h3>
                </div>
                <!-- Light table -->
                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col" class="sort" data-sort="name">No</th>
                                <th scope="col" class="sort" data-sort="budget">Name</th>
                                <th scope="col" class="sort" data-sort="status">URL</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="list">
                            @foreach ($movies as $item)
                                <tr>
                                    <td class="budget">
                                        {{ $loop->iteration }}
                                    </td>
                                    <th scope="row">
                                        <div class="media align-items-center">
                                            <a href="#" class="avatar rounded-circle mr-3">
                                                <img alt="Image placeholder" src="{{ $item->image }}">
                                            </a>
                                            <div class="media-body">
                                                <span class="name mb-0 text-sm">{{ $item->name }}</span>
                                            </div>
                                        </div>
                                    </th>
                                    <td>
                                        {{ $item->url }}
                                    </td>
                                    <td>

                                        <form action="{{ route('movie.destroy', $item->id) }}" method="POST">
                                            @method('DELETE')
                                            @csrf
                                            <button type="submit"><i class="fa fa-trash"
                                                    style="font-size: 20px;"></i></button>


                                        </form>
                                    </td>
                                </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
                <div class="card-footer py-4">
                    {{ $movies->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection